### ISSUE TITLE
UDP support?

### ISSUE THREAD

**Issue by ronf** [icgood/proxy-protocol#30]
Thanks very much for providing this library, and for providing examples of both a server and a proxy. It made it very easy to experiment with this!

Do you have any plans to add support for UDP (SOCK_DGRAM) traffic over proxy protocol v2? I've been reading the spec at https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt to try and figure out what things look like on the wire in that case, but I've been unable to find any client or server implementations I could use as an example. It looks like HAProxy may not support UDP, and even NGINX which does support UDP may not support proxy protocol for it. I see signs that some cloud provider load balancers support UDP, but I don't have a setup which allows me to easily test in any of those environments right now.

In particular, it isn't clear to me whether the proxy protocol header is added to every UDP packet or only at the start of a new flow. If it is only added at the start, it isn't clear to me how servers would recover if the packet with this header was lost in transit, or if it arrived out of order.

The closest thing I've found so far is from CloudFlare at https://developers.cloudflare.com/spectrum/proxy-protocol which says for UDP that the proxy protocol v2 header will be prepended to the first packet on a stream, but this doesn't seem to address recovery in the case of packet loss or reordering.  That link also describes an alternative "simple proxy protocol" header which is specifically for UDP and puts the header at the beginning of every UDP packet. However, that seems to be a CloudFlare-specific alternative to proxy protocol v2 and I'm not sure that would be available anywhere else.

If you have any more information on support for UDP with proxy protocol v2 in general, that would also be appreciated!

**Comment by icgood** [comment]
Hi @ronf, for all the reasons you seem to have discovered, proxy protocol isn't really well suited (or _easily_ suited) to UDP. Due to datagram packet size limitations, it's not necessarily safe to just add a header to every packet unless the application protocol is guaranteed to leave enough room.

One possibility would be to send a packet that contains the full proxy protocol header (v2 + TLV can be a few hundred bytes) and subsequent application packets could simply reference the header (e.g. by hash), assuming that each source is cached on the receiver side. I don't think something like that could be made generic enough to include in this library, especially without inclusion in the proxy protocol spec, but it could work for your situation.

Hope that helps, feel free to reopen if you have any more questions or ideas.

**Comment by ronf** [comment]
Thanks for getting back to me. I agree with the concerns you mentioned around length. Adding such a header in every packet would probably not exceed the max UDP datagram size, but it could lead to IP fragmentation if the original UDP packets were already close to the MTU in size, and having every packet fragmented is far from ideal.

There's also an ordering and packet loss concern with the "hash" approach, if the initial packet with the full header is dropped or if it arrives out of order and the receiver gets a packet with the hash in it before the one with the full header.

To be clear, my original question was to try and get clarity on the current proxy protocol v2 spec and not to ask for something new to be implemented. It seems like maybe there isn't an implementation that addresses these issues, though, despite to spec mentioning UDP as one of the options.
